### ISSUE TITLE
Kubespray: Failed to run on centos with Vagrant

### ISSUE THREAD

**Issue by oomichi** [oomichi/try-kubernetes#119]
```
$ cat vagrant/config.rb 
$num_instances = 1
$os = "centos"
$
$ vagrant up
...
TASK [kubernetes/preinstall : Stop if ip var does not match local ips] *********
fatal: [k8s-1]: FAILED! => {
    "assertion": "ip in ansible_all_ipv4_addresses",
    "changed": false,
    "evaluated_to": false,
    "msg": "'['192.168.121.59']' do not contain '172.18.8.101'"
}
```

**Comment by oomichi** [comment]
role/kubernetes/preinstall/tasks/0020-verify-settings.yml
```
- name: Stop if ip var does not match local ips
  assert:
    that: ip in ansible_all_ipv4_addresses
    msg: "'{{ ansible_all_ipv4_addresses }}' do not contain '{{ ip }}'"
  when:
    - not ignore_assert_errors
    - ip is defined
```
- ansible_all_ipv4_addresses: ['192.168.121.59']
- ip: 172.18.8.101

```
$ ip addr 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:66:20:26 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.59/24 brd 192.168.121.255 scope global noprefixroute dynamic eth0
       valid_lft 2082sec preferred_lft 2082sec
    inet6 fe80::5054:ff:fe66:2026/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:97:13:e2 brd ff:ff:ff:ff:ff:ff
    inet6 fd3c:b398:698:756:cb8b:7f19:2bc0:b562/64 scope global noprefixroute dynamic 
       valid_lft 3335sec preferred_lft 3335sec
    inet6 fe80::da89:244:7083:f1ff/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
