### ISSUE TITLE
preStop hook調査

### ISSUE THREAD

**Issue by oomichi** [oomichi/try-kubernetes#121]
[ドキュメント](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#discussion) にはpreStop hookの挙動について以下のように記載されているが、
```
Note: Kubernetes only sends the preStop event when a Pod is terminated.
This means that the preStop hook is not invoked when the Pod is completed.
```
LivenessProve/Startup失敗時にpod内のコンテナが終了した際にもpreStop hookは呼ばれるため、実際の挙動と異なる。
"when a Pod is terminated"とは少し異なると考えられる。
したがって、ドキュメントを下記のとおり修正して欲しい。
```
Kubernetes only sends the preStop event when a Pod or a container in the Pod is terminated.
This means that the preStop hook is not invoked when the Pod is completed.
```

**Comment by oomichi** [comment]
Mori-san:
上記の投稿内容に対し、ローカル環境で以下の手順で動作確認を実施しました。
以下のyamlファイルを作成（liveness-check.yaml）
```
apiVersion: v1
kind: Pod
metadata:
  name: liveness-check
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
        path: /
      failureThreshold: 5
      periodSeconds: 5
    lifecycle:
      preStop:
        exec:
          command: ["/usr/sbin/nginx","-s","quit"]
```
2. 上記のyamlファイルからpodを作成
```
$ kubectl apply -f liveness-check.yaml
```
3. /usr/share/nginx/html/index.html を削除する
```
$ kubectl exec liveness-check -- rm /usr/share/nginx/html/index.html
```
4. podの詳細を確認する
```
$ kubectl describe pod liveness-check
...
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  7m34s                  default-scheduler  Successfully assigned default/liveness-check to test-worker
  Normal   Pulled     7m30s                  kubelet            Successfully pulled image "nginx" in 2.291357524s
  Warning  Unhealthy  6m29s (x5 over 6m49s)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 403
  Normal   Killing    6m29s                  kubelet            Container nginx failed liveness probe, will be restarted
  Normal   Pulling    6m28s (x2 over 7m32s)  kubelet            Pulling image "nginx" 
  Normal   Pulled     6m26s                  kubelet            Successfully pulled image "nginx" in 2.119307294s
  Normal   Created    6m24s (x2 over 7m29s)  kubelet            Created container nginx
  Normal   Started    6m24s (x2 over 7m28s)  kubelet            Started container nginx
```
